/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../stm_driver/inc/Stm32_F103C6_EXTI_driver.h"
#include "../stm_driver/inc/Stm32_F103C6_gpio_driver.h"
#include "../CMSIS_V5/core_cm3.h"
#include "../RTOS/inc/Schedular.h"
#include "string.h"


Task_Config Task1, Task2, Task3;

uint8_t Task1Indication,Task2Indication,Task3Indication;


void task1()
{
	while(1){
		// Task1 Code
		Task1Indication^=1;
	}
}

void task2()
{
	while(1){
		// Task1 Code
		Task2Indication^=1;
	}
}

void task3()
{
	while(1){
		// Task1 Code
		Task3Indication ^= 1;
	}
}

int main(void)
{
	MYRTOS_errorID Error = NO_ERROR;
	// HW_Init	(Initialize clockTree, ResetController)
	HW_Init();

	if(MYRTOS_Init() != NO_ERROR)
		while(1);


	// Create tasks
	Task1.Stack_Size = 1024;   // 1kByte
	Task1.P_TaskEntry = task1;
	Task1.Priority = 3;
	strcpy(Task1.TaskName, "task_1");

	Task2.Stack_Size = 1024;   // 1kByte
	Task2.P_TaskEntry = task2;
	Task2.Priority = 3;
	strcpy(Task2.TaskName, "task_2");

	Task3.Stack_Size = 1024;   // 1kByte
	Task3.P_TaskEntry = task3;
	Task3.Priority = 7;
	strcpy(Task3.TaskName, "task_3");

	Error += MYRTOS_Create_Task(&Task1);
	Error += MYRTOS_Create_Task(&Task2);
	Error += MYRTOS_Create_Task(&Task3);

	MYRTOS_Activate_Task(&Task1);
	MYRTOS_Activate_Task(&Task2);
	MYRTOS_Activate_Task(&Task3);

	MYRTOS_START_OS();

	while(1)
	{



	}
}



